---
- name: Basic Initial Setup for Ubuntu
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install common packages
      ansible.builtin.apt:
        name:
          - git
          - curl
          - vim
        state: present
